site_name: ace

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
plugins:
  - search

theme:
  name: material

  logo_dark_mode: 'img/logo-dark.png'
  logo_light_mode: 'img/logo-light.png'

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  generator: false

copyright: Copyright &copy; 2023 - 2025 pgEdge, Inc
repo_url: https://github.com/pgEdge/ace

nav:
  - ACE Overview: index.md
  - Best Practices for Using ACE: best_practices.md
  - ACE Configuration: configuration.md
  - 'ACE Commands':
    - 'Command reference': commands/index.md
    - 'Diff Commands':
      - 'Overview': commands/diff/index.md
      - 'table-diff': commands/diff/table-diff.md
      - 'repset-diff': commands/diff/repset-diff.md
      - 'schema-diff': commands/diff/schema-diff.md
      - 'spock-diff': commands/diff/spock-diff.md
      - 'table-rerun': commands/diff/table-rerun.md
    - 'Repair Commands':
      - 'Overview': commands/repair/index.md
      - 'table-repair': commands/repair/table-repair.md
    - 'Merkle Tree Commands':
      - 'Overview': commands/mtree/index.md
      - 'mtree-build': commands/mtree/mtree-build.md
      - 'mtree-init': commands/mtree/mtree-init.md
      - 'mtree-listen': commands/mtree/mtree-listen.md
      - 'mtree-table-diff': commands/mtree/mtree-table-diff.md
      - 'mtree-teardown-table': commands/mtree/mtree-teardown-table.md
      - 'mtree-teardown': commands/mtree/mtree-teardown.md
      - 'mtree-update': commands/mtree/mtree-update.md
  - Scheduling ACE Runs: scheduling.md
  - The ACE API: api.md
  - Improving ACE Performance: performance.md
  - Release Notes: CHANGELOG.md 